services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=favourite-recipes
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  favourite-recipes-app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    labels:
      container-name: favourite-recipes-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/favourite-recipes"
      SPRING_DATASOURCE_USER: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    volumes:
      - ../:/production

volumes:
  postgres:
    driver: local