spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/favourite-recipes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: favourite-recipes-pool
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedStatements: true
        socketTimeout: 30 #default 0s
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: none
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
  mvc:
    problemdetails:
      enabled: true
